language: node_js

node_js:
  - 'stable'

before_install: cd exam_2

dist: trusty

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build

addons:
  apt:
    packages:
      - libnss3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam_2/build
  on:
    branch:
      - master
      - devel
      - exam_2
