language: node_js

node_js:
  - 'stable'

dist: trusty

warnings_are_errors: false

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build

addons:
  apt:
    packages:
      - libnss3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: build
  on:
    branch:
      - master
      - devel
