version: '3.6'
services:
  exam:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'development'
    volumes:
      - .:/code
      - /code/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3000:3000'
    networks:
      - webnet
    environment:
      HOST: '0.0.0.0'

networks:
  webnet:
